s=set()
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
a=input("enter a number\n")
s.add(int(a))
print(s)