dict={}
a=input("enter the person name \n")
b=input("enter the language name \n")
dict.update({a:b})
a=input("enter the person name \n")
b=input("enter the language name \n")
dict.update({a:b})
a=input("enter the person name \n")
b=input("enter the language name \n")
dict.update({a:b})
a=input("enter the person name \n")
b=input("enter the language name \n")
dict.update({a:b})
a=input("enter the person name \n")
b=input("enter the language name \n")
dict.update({a:b})
a=input("enter the person name \n")
b=input("enter the language name \n")
dict.update({a:b})
print(dict)
#values may be same but keys should be unique