#7 MARKS LIST
MARKS=[]
f1=int(input("enter marks \n"))
MARKS.append(f1)
f1=int(input("enter marks \n"))
MARKS.append(f1)
f1=int(input("enter marks \n"))
MARKS.append(f1)
f1=int(input("enter marks \n"))
MARKS.append(f1)
f1=int(input("enter marks \n"))
MARKS.append(f1)
f1=int(input("enter marks \n"))
MARKS.append(f1)
f1=int(input("enter marks \n"))
MARKS.append(f1)
MARKS.sort()
print(MARKS)